website = {
    # --- PDF MODIFIERS & TOOLS ---
    "ilovepdf": "https://www.ilovepdf.com",
    "smallpdf": "https://smallpdf.com",
    "adobe acrobat": "https://www.adobe.com/acrobat/online.html",
    "pdf2go": "https://www.pdf2go.com",
    "soda pdf": "https://www.sodapdf.com",
    "sejda": "https://www.sejda.com",
    "pdfcandy": "https://pdfcandy.com",
    "pdffiller": "https://www.pdffiller.com",
    "avepdf": "https://avepdf.com",
    "foxit": "https://www.foxit.com/online-pdf-tools",
    "pdfescape": "https://www.pdfescape.com",
    "cleverpdf": "https://www.cleverpdf.com",
    "xodo": "https://xodo.com",
    "pdf converter": "https://www.freepdfconvert.com",
    "pdfresizer": "https://pdfresizer.com",
    # --- SOCIAL MEDIA & VIDEO (15) ---
    "facebook": "https://facebook.com",
    "instagram": "https://instagram.com",
    "youtube": "https://youtube.com",
    "twitter": "https://x.com",
    "linkedin": "https://linkedin.com",
    "whatsapp": "https://web.whatsapp.com",
    "reddit": "https://reddit.com",
    "pinterest": "https://pinterest.com",
    "snapchat": "https://snapchat.com",
    "discord": "https://discord.com",
    "telegram": "https://web.telegram.org",
    "tiktok": "https://tiktok.com",
    "threads": "https://threads.net",
    "quora": "https://quora.com",
    "twitch": "https://twitch.tv",
    # --- OFFICIAL INDIAN GOVT PORTALS (STRICTLY OFFICIAL) ---
    "aadhar card": "https://uidai.gov.in",
    "pan card": "https://incometaxindia.gov.in/Pages/tax-services/apply-for-pan.aspx",
    "passport": "https://www.passportindia.gov.in",
    "voter id": "https://voters.eci.gov.in",
    "income tax efiling": "https://www.incometax.gov.in",
    "digilocker": "https://www.digilocker.gov.in",
    "parivahan": "https://parivahan.gov.in",
    "epfo": "https://www.epfindia.gov.in",
    "irctc": "https://www.irctc.co.in",
    "gst": "https://www.gst.gov.in",
    "mca": "https://www.mca.gov.in",
    "mygov": "https://www.mygov.in",
    "nsp": "https://scholarships.gov.in",
    "digital india": "https://www.digitalindia.gov.in",
    "umang": "https://web.umang.gov.in",
    # --- OFFICIAL BANKING PORTALS (STRICTLY OFFICIAL) ---
    "sbi": "https://www.onlinesbi.sbi",
    "hdfc": "https://www.hdfcbank.com",
    "icici": "https://www.icicibank.com",
    "axis": "https://www.axisbank.com",
    "pnb": "https://www.pnbindia.in",
    "bank of baroda": "https://www.bankofbaroda.in",
    "canara bank": "https://canarabank.com",
    "union bank": "https://www.unionbankofindia.co.in",
    "kotak": "https://www.kotak.com",
    "idfc first": "https://www.idfcfirstbank.com",
    "yes bank": "https://www.yesbank.in",
    "rbi": "https://www.rbi.org.in",
    "indusind": "https://www.indusind.com",
    "federal bank": "https://www.federalbank.co.in",
    "bank of india": "https://www.bankofindia.co.in",
    # --- AI TOOLS ---
    "chatgpt": "https://chatgpt.com",
    "gemini": "https://gemini.google.com",
    "claude": "https://claude.ai",
    "perplexity": "https://www.perplexity.ai",
    "midjourney": "https://www.midjourney.com",
    "bing ai": "https://www.bing.com/chat",
    "copilot": "https://copilot.microsoft.com",
    "jasper": "https://www.jasper.ai",
    "quillbot": "https://quillbot.com",
    "grammarly": "https://www.grammarly.com",
    "hugging face": "https://huggingface.co",
    "did": "https://www.d-id.com",
    "elevenlabs": "https://elevenlabs.io",
    "synthesia": "https://www.synthesia.io",
    "deepai": "https://deepai.org",
    # --- SHOPPING & FOOD ---
    "amazon": "https://www.amazon.in",
    "flipkart": "https://www.flipkart.com",
    "myntra": "https://www.myntra.com",
    "ajio": "https://www.ajio.com",
    "nykaa": "https://www.nykaa.com",
    "meesho": "https://www.meesho.com",
    "tata cliq": "https://www.tatacliq.com",
    "bigbasket": "https://www.bigbasket.com",
    "blinkit": "https://blinkit.com",
    "swiggy": "https://www.swiggy.com",
    "zomato": "https://www.zomato.com",
    "zepto": "https://www.zepto.com",
    "jiomart": "https://www.jiomart.com",
    "lenskart": "https://www.lenskart.com",
    "firstcry": "https://www.firstcry.com",
    "pizza hut": "https://pizzahut.co.in",
    "dominos": "https://dominos.co.in",
    # --- VIDEO & MUSIC ---
    "netflix": "https://www.netflix.com",
    "prime video": "https://www.primevideo.com",
    "hotstar": "https://www.hotstar.com",
    "zee5": "https://www.zee5.com",
    "jio cinema": "https://www.jiocinema.com",
    "spotify": "https://open.spotify.com",
    "youtube music": "https://music.youtube.com",
    "gaana": "https://gaana.com",
    "jiosaavn": "https://www.jiosaavn.com",
    "wynk": "https://wynk.in",
    "apple music": "https://music.apple.com",
    "soundcloud": "https://soundcloud.com",
    "hungama": "https://www.hungama.com",
    "twitch": "https://www.twitch.tv",
    "vimeo": "https://vimeo.com",
    # --- RECIPES ---
    "allrecipes": "https://allrecipes.com",
    "food network": "https://foodnetwork.com",
    "sanjeev kapoor": "https://sanjeevkapoor.com",
    "hebbars kitchen": "https://hebbarskitchen.com",
    "veg recipes of india": "https://vegrecipesofindia.com",
    "tarladalal": "https://tarladalal.com",
    "bbcfood": "https://bbc.co.uk/food",
    "epicurious": "https://epicurious.com",
    "serious eats": "https://seriouseats.com",
    "bon appetit": "https://bonappetit.com",
    "the spruce eats": "https://thespruceeats.com",
    "pinch of yum": "https://pinchofyum.com",
    "cookie and kate": "https://cookieandkate.com",
    "food52": "https://food52.com",
    "simply recipes": "https://simplyrecipes.com",
    # --- UTILITIES & SERVICE CENTERS ---
    "weather": "https://weather.com",
    "accuweather": "https://accuweather.com",
    "imd": "https://mausam.imd.gov.in",
    "apple": "https://support.apple.com/en-in",
    "samsung": "https://samsung.com/in/support",
    "hp": "https://support.hp.com/in-en",
    "dell": "https://dell.com/support/home/en-in",
    "lenovo": "https://support.lenovo.com/in/en",
    "asus": "https://asus.com/in/support",
    "acer": "https://acer.com/in-en/support",
    "boat": "https://support.boat-lifestyle.com",
    "mi": "https://mi.com/in/service/repair",
    "realme": "https://realme.com/in/support",
    "oppo": "https://support.oppo.com/in",
    "vivo": "https://vivo.com/in/support",
    # --- SEARCH & EMAIL ---
    "google": "https://google.com",
    "bing": "https://bing.com",
    "duckduckgo": "https://duckduckgo.com",
    "yahoo": "https://yahoo.com",
    "baidu": "https://baidu.com",
    "yandex": "https://yandex.com",
    "aol": "https://aol.com",
    "gmail": "https://mail.google.com",
    "outlook": "https://outlook.com",
    "icloud": "https://icloud.com/mail",
    "protonmail": "https://proton.me",
    "zoho mail": "https://zoho.com/mail",
    "gmx": "https://gmx.com",
    "mail": "https://mail.com",
    "tutanota": "https://tuta.com",
}
